typedef enum {
    CONTROL_MODE_JOYSTICK,
    CONTROL_MODE_GRAVITY,
    CONTROL_MODE_EVADIBLE,
    CONTROL_MODE_FOLLOW,
    CONTROL_MODE_RGB_MODE_OFF,
    CONTROL_MODE_RGB_MODE_BREATHING,
    CONTROL_MODE_RGB_MODE_RUNNING,
    CONTROL_MODE_RGB_MODE_FLASHING,
} control_mode_t;

typedef enum {
    RGB_MODE_OFF,
    RGB_MODE_BREATHING,
    RGB_MODE_RUNNING,
    RGB_MODE_FLASHING,
} rgb_mode_t;